site_name: 'Links box'
site_description: 'This website lists some tools, posts and other stuffs I like.'
site_author: 'Marc-Henry GEAY'
site_url: 'https://mhg.ovh'
copyright: '<a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>'
use_directory_urls: false
theme:
  name: material
  language: en
  favicon: assets/flask-outline.svg
  font: false
  icon:
    logo: material/flask-outline
  palette:
    scheme: preference
    primary: light green
    accent: light green
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mhgeay
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mhgeay
    - icon: fontawesome/brands/github
      link: https://github.com/mhgeay
markdown_extensions:
  - meta
  - toc:
      permalink: true
plugins:
  - search
  - git-revision-date